# Zsh Config
export PATH=~/.composer/vendor/bin:$PATH

# Enable colors
autoload -U colors
colors
export CLICOLOR=1

# Shell prompt
PS1="%F{green}%B$%b%{$reset_color%} "

# Reset $WORDCHARS variable to match RegExp \w
WORDCHARS='_'

# Refresh tmux status bar
. ~/.scripts/tmux-update-status.sh

export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh
